name: SportBoard-container

services:
    postgres:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: postgres

    kong-migrations:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: kong-migrations

    kong:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: kong

# Microservicio de catálogo
#    sqlserver:
#        extends:
#            file: ./backend/ms6-catalog/docker-compose.override.yml
#            service: sqlserver
#    
#    catalogs:
#        extends:
#            file: ./backend/ms6-catalog/docker-compose.override.yml
#            service: catalogs

# Microservicio Tiempo Real
    ms3-real-time:
        extends:
            file: ./backend/ms3-real-time/docker-compose.override.yml
            service: ms3-real-time

    mariadb-real-time:
        extends:
            file: ./backend/ms3-real-time/docker-compose.override.yml
            service: mariadb-real-time
# Microservicio de competencias
    ms2-competencies:
        extends:
            file: ./backend/ms2-competencies/docker-compose.override.yml
            service: ms2-competencies
        networks:
            - sportboard-network

    postgres-competencies:
        extends:
            file: ./backend/ms2-competencies/docker-compose.override.yml
            service: postgres-competencies

networks:
    sportboard-network:
        name: sportboard-network
        driver: bridge

volumes:
    mariadb_data:
    static_volume:
