_format_version: "2.1"
_transform: true

services:
  - name: groups-service
    url: http://catalogs:5241/api/groups
    routes:
      - name: groups-route
        paths:
          - /catalog/groups
  - name: catalogs-service
    url: http://catalogs:5241/api/catalogs
    routes:
      - name: catalogs-route
        paths:
          - /catalog/catalogs
  - name: real-time-service
    url: http://ms3-real-time:5000/api  
    routes:
      - name: matches-route
        paths:
          - /api/partidos
      - name: events-route
        paths:
          - /api/eventos

  - name: ms2-competencies
    url: http://ms2-competencies:8003
    routes:
      - name: ms2-competencies-route
        paths:
          - /api
        strip_path: false
  - name: static-files
    url: http://ms2-competencies:8003
    routes:
      - name: static-files-route
        paths:
          - /static/
        strip_path: false
  - name: media-files
    url: http://ms2-competencies:8003
    routes:
      - name: media-files-route
        paths:
          - /media/
        strip_path: false
